apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-questioner
  namespace: pod-observer
  labels:
    app: k8s-questioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-questioner
  template:
    metadata:
      labels:
        app: k8s-questioner
    spec:
      serviceAccountName: pod-observer
      containers:
      - name: k8s-questioner
        image: eilon01/k8s-questioner:5a50f2c
        ports:
        - name: http
          containerPort: 80