apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-questioner
  namespace: pod-observer
  labels:
    app: k8s-questioner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-questioner
  template:
    metadata:
      labels:
        app: k8s-questioner
    spec:
      serviceAccountName: k8s-questioner
      containers:
      - name: k8s-questioner
        image: eilon01/k8s-questioner:6e8d7c6
        ports:
        - name: http
          containerPort: 80