apiVersion: v1
kind: Service
metadata:
  name: k8s-questioner
  namespace: pod-observer
spec:
  type: ClusterIP  
  ports:
  - port: 80       
    targetPort: 80 
    protocol: TCP
  selector:
    app: k8s-questioner 