apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-observer
  namespace: {{ .Values.namespace }}
  labels:
    app: pod-observer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-observer
  template:
    metadata:
      labels:
        app: pod-observer
    spec:
      containers:
      - name: pod-observer
        image: eilon01/k8s-questioner:6e8d7c6
        ports:
        - name: http
          containerPort: 80
        env:
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: pod-observer
              key: SLACK_TOKEN
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              name: pod-observer
              key: SLACK_SIGNING_SECRET
