apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pod-observer
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: my-k8s-lab.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pod-observer
            port:
              number: 80