apiVersion: v1
kind: Service
metadata:
  name: pod-observer
  namespace: pod-observer
spec:
  type: ClusterIP  
  ports:
  - port: 80       
    targetPort: 5000 
    protocol: TCP
  selector:
    app: pod-observer 