apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pod-observer
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: pod-observer
  namespace: pod-observer
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: pod-observer
  source:
    path: helm-chart/pod-observer
    repoURL: git@github.com:Eilon01/podobserver.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true