kind: ConfigMap
apiVersion: v1
metadata:
  name: pod-observer
  namespace: {{ .Values.global.namespace }}
data:
  K8S_QUESTIONER_SERVICE: {{ .Values.podObserver.configMap.data.K8S_QUESTIONER_SERVICE }}
  K8S_QUESTIONER_PORT: {{ .Values.podObserver.configMap.data.K8S_QUESTIONER_PORT }}