apiVersion: v1
kind: Secret
metadata:
  name: pod-observer
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  SLACK_TOKEN: {{ .Values.SLACK_TOKEN }}
  SLACK_SIGNING_SECRET: {{ .Values.SLACK_SIGNING_SECRET }}