apiVersion: v1
kind: Service
metadata:
  name: pod-observer
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: pod-observer 
  type: {{ .Values.podObserver.service.serviceType }}  
  ports:
  - name: pod-observer
    protocol: {{ .Values.podObserver.service.protocol }}
    port: {{ .Values.podObserver.service.port }}
    targetPort: {{ .Values.podObserver.deployment.container.port.portName }}