apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: k8s-questioner
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: k8s-questioner
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.global.namespace }}
      podSelector:
        matchLabels:
          app: pod-observer
    ports:
    - protocol: TCP
      port: {{ .Values.podObserver.service.port }}
    - protocol: TCP
      port: {{ .Values.podObserver.deployment.container.port.containerPort }}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.global.namespace }}
      podSelector:
        matchLabels:
          app: pod-observer
    ports:
    - protocol: TCP
      port: {{ .Values.podObserver.service.port }}
    - protocol: TCP
      port: {{ .Values.podObserver.deployment.container.port.containerPort }}
  {{- range (lookup "v1" "Endpoints" "default" "kubernetes").subsets }}
  - to:
      {{- range .addresses }}
      - ipBlock:
          cidr: {{ .ip }}/32
      {{- end }}
    ports:
      {{- range .ports }}
      - protocol: {{ .protocol }}
        port: {{ .port }}
      {{- end }}
  {{- end }}