apiVersion: v1
kind: Service
metadata:
  name: k8s-questioner
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.k8sQuestioner.service.serviceType }}  
  ports:
    - protocol: {{ .Values.k8sQuestioner.service.protocol }}
      port: {{ .Values.k8sQuestioner.service.port }}
      targetPort: {{ .Values.k8sQuestioner.deployment.container.port.portName }}
  selector:
    app: k8s-questioner 