name:  Build, Push and Update Values.yaml
on:
  push:
    branches:
      - main

jobs:
  build-apps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        apps: [pod-observer, k8s-questioner]
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short commit SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: app/${{ matrix.apps}}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.apps}}:${{ env.SHORT_SHA }}


  update-tag:
    runs-on: ubuntu-latest
    needs: [build-apps]
    strategy:
      matrix:
        apps: [pod-observer, k8s-questioner]

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4 
      
      - name: Get short commit SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      
        # sed -i "s/tag: .*/tag: ${SHORT_SHA}/" helm-chart/values.yaml
      - name: update values.yaml with new tag 
        run: |
          sed -i "s/image: eilon01/${{ matrix.apps}}: .*/image: eilon01/pod-${{ matrix.apps}}: ${SHORT_SHA}/" helm-chart/templates/${{ matrix.apps}}/deployment.yaml

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Apps Image Tag to ${{ env.SHORT_SHA }}"
          branch: main
          file_pattern: helm-chart/values.yaml
          